# azure-pipelines.yml

trigger:
- main

pool:
  vmImage: windows-latest

stages:
- stage: TF_VALIDATE
  jobs:
  - job:
    steps:

    - task: TerraformInstaller@0
      displayName: TF_Install
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTaskV3@3
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'SPN-Project05'
        backendAzureRmResourceGroupName: 'S2-RG-Project05-CORE'
        backendAzureRmStorageAccountName: 'storagecrproject05230710'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'main.tfstate'