# azure-pipelines.yml

trigger:
- main

pool:
  vmImage: windows-latest

stages:
- stage: TF_VALIDATE
  jobs:
  - job:
    steps:

    - task: TerraformInstaller@0
      displayName: TF_Install
      inputs:
        terraformVersion: 'latest'

